# Generated by Django 4.2.1 on 2023-05-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('imageLink', models.URLField()),
                ('language', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
